# Generated by Django 5.1 on 2024-09-14 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PVCalculatorApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inverter',
            old_name='optimal_input_voltage',
            new_name='opt_input_voltage',
        ),
    ]
