# Generated by Django 5.1 on 2024-09-15 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PVCalculatorApp', '0002_rename_optimal_input_voltage_inverter_opt_input_voltage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='name',
        ),
        migrations.CreateModel(
            name='StringPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string1', models.IntegerField()),
                ('string2', models.IntegerField()),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='string_pairs', to='PVCalculatorApp.solutionproject')),
            ],
        ),
    ]
