# Generated by Django 5.1 on 2024-09-20 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PVCalculatorApp', '0009_remove_myuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionproject',
            name='solution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PVCalculatorApp.solution'),
        ),
        migrations.RemoveField(
            model_name='solutionproject',
            name='project',
        ),
        migrations.AddField(
            model_name='solutionproject',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PVCalculatorApp.project'),
        ),
    ]
