# Generated by Django 5.1 on 2024-09-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PVCalculatorApp', '0010_solutionproject_solution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(default='Unnamed Project', max_length=64),
        ),
    ]
