# Generated by Django 5.1 on 2024-09-24 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PVCalculatorApp', '0011_alter_project_project_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panel',
            old_name='ISC_amper',
            new_name='isc_amper',
        ),
        migrations.RenameField(
            model_name='panel',
            old_name='TMOD_pMax_percent',
            new_name='tmod_p_max_percent',
        ),
        migrations.RenameField(
            model_name='panel',
            old_name='TMOD_percent',
            new_name='tmod_percent',
        ),
        migrations.RenameField(
            model_name='panel',
            old_name='TMOD_short_percent',
            new_name='tmod_short_percent',
        ),
        migrations.RenameField(
            model_name='panel',
            old_name='UmmpMOD_volt',
            new_name='ummp_mod_volt',
        ),
        migrations.RenameField(
            model_name='panel',
            old_name='UocMOD_volt',
            new_name='uoc_mod_volt',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='nDCmaxINV',
            new_name='ndc_max_inv',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='nDCminINV',
            new_name='ndc_min_inv',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='nDCoptINV',
            new_name='ndc_opt_inv',
        ),
    ]
